name = "shhh"
main = "src/worker/index.ts"
compatibility_date = "2025-02-14"
compatibility_flags = ["nodejs_compat"]
account_id = "6a9e4591f2bb3711c87592659eeee480"

routes = [
  { pattern = "shhh.riskscope-consulting.com/*", zone_name = "riskscope-consulting.com" },
  { pattern = "share.riskscope-consulting.com/*", zone_name = "riskscope-consulting.com" }
]

[assets]
directory = "./dist/client"
binding = "ASSETS"
not_found_handling = "single-page-application"

[observability]
enabled = true

[[kv_namespaces]]
binding = "SECRETS"
id = "0ba6afaf178f45a48e55cdcb22740435"
preview_id = "0985267727ff4f8d890fdfefae7fc04b"

[[kv_namespaces]]
binding = "RATE_LIMITS"
id = "53817d6363644972af3652d9b30fa880"
preview_id = "68ad8115e6054656b31022d31e1fe2d2"

[[r2_buckets]]
binding = "FILES"
bucket_name = "shhh-files"
preview_bucket_name = "shhh-files-preview"
